# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Yuan Qu
email: yuan.qu@rutgers.edu
description: >- # this means to ignore newlines until "baseurl:"
  Yuan Qu, a Ph.D. Candidate in Operation Research at Rutgers University, supervised by Prof. Endre Boros and Prof. Hui Xiong.
  I received my M.Sc. degree in Information Technology for Rutgers University, and B.Sc. and B.A. degrees from UESTC, China.
  Research Interests: My interests lie broadly in optimization and machine learning, especially for discrete optimization and AI in marketing. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.ryanqu.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
remote_theme: thelehhman/plainwhite-jekyll
plugins:
  - jekyll-feed

plainwhite:
  name: Yuan Qu
  tagline: Ph.D. Candidate. Developer.
  date_format: "%b %-d, %Y"

  social_links:
    twitter: ryanqu94
    github: RyanQu
    linkedIn: in/ryanqu # format: locale/username

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
